version: '2'
volumes:
  apk-volume:
services:
  server:
    build: ./server
    ports:
    - "8080:8080"
    depends_on:
    - database
    - redis
  client_web:
    volumes:
    - apk-volume:/usr/src/app/dist
    build: ./web_client
    ports:
    - "8081:8081"
    depends_on:
    - server
  client_mobile:
    volumes:
    - apk-volume:/usr/src/apk
    build: ./mobile_client
    depends_on:
    - client_web
  database:
    image: postgres:9.6.8-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123soleil
      POSTGRES_DB: area
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
